### ISSUE TITLE
Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.

### ISSUE THREAD

**Issue by realajay** [bndynet/web-framework-for-java#53]
没有做任何代码修改，编译然后运行报此错误。

**Comment by bndynet** [comment]
@realajay  Do you start app by running `mvn spring-boot:run`?  pls ensure all dependencies are installed before that. If the error still exists, pls provide more information or screenshots.

**Comment by realajay** [comment]
@bndynet 已经找到了问题所在。是由idea造成的，`<scope>provided</scope>` 在idea中运行时不被引用，将其修改为`compile`就可以了。
`mvn spring-boot:run`没有问题，一切正常。
